// Auto-generated by: pnpm db:types
// Run `pnpm db:types` after `supabase start` + `supabase db reset` to regenerate.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type UserRole = 'owner' | 'admin' | 'member'
export type OrgPlan = 'free' | 'pro' | 'premium'

// Mirrors the shape supabase-js's GenericSchema constraint requires.
export type Database = {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string
          name: string
          plan: OrgPlan
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          plan?: OrgPlan
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          plan?: OrgPlan
          created_by?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          id: string
          full_name: string | null
          phone: string | null
          preferred_language: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          full_name?: string | null
          phone?: string | null
          preferred_language?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string | null
          phone?: string | null
          preferred_language?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      memberships: {
        Row: {
          id: string
          org_id: string
          user_id: string
          role: UserRole
          created_at: string
        }
        Insert: {
          id?: string
          org_id: string
          user_id: string
          role?: UserRole
          created_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          user_id?: string
          role?: UserRole
          created_at?: string
        }
        Relationships: []
      }
      clients: {
        Row: {
          id: string
          org_id: string
          full_name: string
          phone: string | null
          email: string | null
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          org_id: string
          full_name: string
          phone?: string | null
          email?: string | null
          created_by?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          full_name?: string
          phone?: string | null
          email?: string | null
          created_by?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      audit_log: {
        Row: {
          id: number
          org_id: string
          actor_id: string | null
          action: string
          entity: string
          entity_id: string | null
          metadata: Json
          created_at: string
        }
        Insert: {
          org_id: string
          actor_id?: string | null
          action: string
          entity: string
          entity_id?: string | null
          metadata?: Json
          created_at?: string
        }
        Update: Record<string, never>
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: {
      create_organization: {
        Args: { p_name: string }
        Returns: {
          id: string
          name: string
          plan: OrgPlan
          created_by: string
          created_at: string
          updated_at: string
        }
      }
      is_member_of: {
        Args: { p_org: string }
        Returns: boolean
      }
      is_admin_of: {
        Args: { p_org: string }
        Returns: boolean
      }
    }
    Enums: {
      user_role: UserRole
      org_plan: OrgPlan
    }
    CompositeTypes: Record<string, never>
  }
}
